influx:
  enabled: true
  url: ${INFLUX_URL:http://localhost:8086}
  token: ${INFLUX_TOKEN:vHGms79bf5fZDmppiP3TlhcHt1inFUmQmCg7URBv5FFnoY5vxDMsTgCrRTp4eWGWST5bbDObuwLAN2UF82YWgQ==}
  org: ${INFLUX_ORG:vivans}
  bucket: ${INFLUX_BUCKET:dcim}
  measurement: ${INFLUX_MEASUREMENT:dcim_sensor}

sensor:
  mqtt:
    enabled: true
    broker-url: tcp://localhost:1883
    client-id: new-sensor-data-server
    topic: dcim/sensor/data

manager:
  service:
    url: http://localhost:8080
    api-key: sensor-data-service
    enabled: true
